### ISSUE TITLE
can't drag in the header area properly

### ISSUE THREAD

**Issue by tomzorz** [tomzorz/Sodalite#8]
![image](https://user-images.githubusercontent.com/6363312/219832360-699fcb56-9379-42ec-893a-f80b26aec64d.png)

**Comment by Technetium1** [comment]
@tomzorz a fix, but not as specific of a selector as it probably could be:
```css
.titlebar {
    -webkit-user-select: none;
	user-select: none;
    -webkit-app-region: drag !important;
}
```
In the meantime, this snippet will fix the problem.
